# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WasteCollectionGroundControl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"WasteCollectionGroundControl.proto\x12\x0fWasteCollection\"=\n\x11VehicleIdentifier\x12\x12\n\nvehicle_id\x18\x01 \x01(\x05\x12\x14\n\x0cvehicle_type\x18\x02 \x01(\t\" \n\x0f\x43ollectionRoute\x12\r\n\x05nodes\x18\x01 \x03(\x05\"Z\n\x15VehicleCurrentContext\x12\x12\n\nvehicle_id\x18\x01 \x01(\x05\x12\x14\n\x0cvehicle_type\x18\x02 \x01(\t\x12\x17\n\x0fremaining_nodes\x18\x03 \x03(\x05\"K\n\x0c\x44ispatchInfo\x12\x12\n\nvehicle_id\x18\x01 \x01(\x05\x12\x14\n\x0cvehicle_type\x18\x02 \x01(\t\x12\x11\n\tstartNode\x18\x03 \x01(\x05\x32\xcb\x01\n\x16WasteCollectionService\x12P\n\x08GetRoute\x12\".WasteCollection.VehicleIdentifier\x1a .WasteCollection.CollectionRoute\x12_\n\x16\x44ispatchAnotherVehicle\x12&.WasteCollection.VehicleCurrentContext\x1a\x1d.WasteCollection.DispatchInfob\x06proto3')



_VEHICLEIDENTIFIER = DESCRIPTOR.message_types_by_name['VehicleIdentifier']
_COLLECTIONROUTE = DESCRIPTOR.message_types_by_name['CollectionRoute']
_VEHICLECURRENTCONTEXT = DESCRIPTOR.message_types_by_name['VehicleCurrentContext']
_DISPATCHINFO = DESCRIPTOR.message_types_by_name['DispatchInfo']
VehicleIdentifier = _reflection.GeneratedProtocolMessageType('VehicleIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLEIDENTIFIER,
  '__module__' : 'WasteCollectionGroundControl_pb2'
  # @@protoc_insertion_point(class_scope:WasteCollection.VehicleIdentifier)
  })
_sym_db.RegisterMessage(VehicleIdentifier)

CollectionRoute = _reflection.GeneratedProtocolMessageType('CollectionRoute', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTIONROUTE,
  '__module__' : 'WasteCollectionGroundControl_pb2'
  # @@protoc_insertion_point(class_scope:WasteCollection.CollectionRoute)
  })
_sym_db.RegisterMessage(CollectionRoute)

VehicleCurrentContext = _reflection.GeneratedProtocolMessageType('VehicleCurrentContext', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLECURRENTCONTEXT,
  '__module__' : 'WasteCollectionGroundControl_pb2'
  # @@protoc_insertion_point(class_scope:WasteCollection.VehicleCurrentContext)
  })
_sym_db.RegisterMessage(VehicleCurrentContext)

DispatchInfo = _reflection.GeneratedProtocolMessageType('DispatchInfo', (_message.Message,), {
  'DESCRIPTOR' : _DISPATCHINFO,
  '__module__' : 'WasteCollectionGroundControl_pb2'
  # @@protoc_insertion_point(class_scope:WasteCollection.DispatchInfo)
  })
_sym_db.RegisterMessage(DispatchInfo)

_WASTECOLLECTIONSERVICE = DESCRIPTOR.services_by_name['WasteCollectionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLEIDENTIFIER._serialized_start=55
  _VEHICLEIDENTIFIER._serialized_end=116
  _COLLECTIONROUTE._serialized_start=118
  _COLLECTIONROUTE._serialized_end=150
  _VEHICLECURRENTCONTEXT._serialized_start=152
  _VEHICLECURRENTCONTEXT._serialized_end=242
  _DISPATCHINFO._serialized_start=244
  _DISPATCHINFO._serialized_end=319
  _WASTECOLLECTIONSERVICE._serialized_start=322
  _WASTECOLLECTIONSERVICE._serialized_end=525
# @@protoc_insertion_point(module_scope)
